### ISSUE TITLE
No active exception to reraise Error

### ISSUE THREAD

**Issue by leon-Glitchking** [chomupashchuk/delete-file-home-assistant#5]
Getting the following Error for both file and folder delete

"
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1487, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/delete/__init__.py", line 39, in handle_delete_file
    raise
RuntimeError: No active exception to reraise
"
and 
"
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1487, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/delete/__init__.py", line 131, in handle_delete_files_in_folder
    raise
RuntimeError: No active exception to reraise
"

have tried 
multiple configurations of the service

"
delete.file
data:
  file: '/share/securitycams/20201013/images/A20101321384110.jpg'
"
and
"
delete.files_in_folder
data:
  folder: /share
  time: 604800
  scan_subfolders: true
  remove_subfolders: true
"

**Comment by chomupashchuk** [comment]
I forgot to chance info's to errors in logger and include description in exceptions. But based on lines the issue is not recognized path by the system (no such folder or file). Please note that folders in frontend and backend for example have totally different paths to the same file and you must use path from backend.

**Comment by chomupashchuk** [comment]
Error description added
